[package]
name = "mupdf"
version = "0.0.6"
authors = ["messense <messense@icloud.com>"]
edition = "2018"
description = "Safe Rust wrapper to MuPDF"
keywords = ["pdf", "mupdf"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/messense/mupdf-rs"

[features]
default = ["js", "xps", "svg", "cbz", "img", "html", "epub"]
sys-lib = ["mupdf-sys/sys-lib"]
js = ["mupdf-sys/js"]
xps = ["mupdf-sys/xps"]
svg = ["mupdf-sys/svg"]
cbz = ["mupdf-sys/cbz"]
img = ["mupdf-sys/img"]
html = ["mupdf-sys/html"]
epub = ["mupdf-sys/epub"]

[dependencies]
mupdf-sys = { version = "0", path = "mupdf-sys" }
once_cell = "1.3.1"
num_enum = "0.5.1"
bitflags = "1.2.1"
font-kit = "0.10.0"

[workspace]
members = [
    ".",
    "mupdf-sys"
]

[dev-dependencies]
crossbeam-utils = "0.8.1"
