[package]
name = "mupdf"
version = "0.0.1"
authors = ["messense <messense@icloud.com>"]
edition = "2018"
description = "Safe Rust wrapper to MuPDF"
keywords = ["pdf", "mupdf"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/messense/mupdf-rs"

[dependencies]
mupdf-sys = { version = "0.0.1", path = "mupdf-sys" }
once_cell = "1.3.1"
num_enum = "0.4.2"
bitflags = "1.2.1"

[workspace]
members = [
    ".",
    "mupdf-sys"
]
